### ISSUE TITLE
A pills mention immediately followed by : does not get converted to a slack mention

### ISSUE THREAD

**Issue by Cadair** [matrix-org/matrix-appservice-slack#318]
I assume there is something broken in the regex which means it needs a space after it. This is frustrating as it's the way riot-web tab completes.

**Comment by auscompgeek** [comment]
Seems like it should accept any word boundary instead.

**Comment by auscompgeek** [comment]
This was fixed by #320, I guess?

**Comment by Cadair** [comment]
This is still present with any character following the pill i.e. `<pill>, <pill>` which is super annoying.
